(define (problem sokoban2) 
    (:domain sokoban)
    (:objects worker1 box1 box2 box3 box4 cell1 cell2 cell3 cell4 cell5 cell6 cell7 cell8 cell9 cell10 cell11 cell12)
    (:init 
        (worker worker1)
        (box box1)
        (box box2)
        (box box3)
        (box box4)
        (cell cell1)
        (cell cell2)
        (cell cell3)
        (cell cell4)
        (cell cell5)
        (cell cell6)
        (cell cell7)
        (cell cell8)
        (cell cell9)
        (cell cell10)
        (cell cell11)
        (cell cell12)
        (under cell2 cell1)
        (under cell3 cell2)
        (left cell3 cell4)
        (left cell4 cell5)
        (left cell5 cell6)
        (under cell9 cell3)
        (left cell7 cell8)
        (left cell8 cell9)
        (left cell9 cell10)
        (under cell10 cell4)
        (under cell11 cell10)
        (under cell12 cell11)
        (empty cell1)
        (empty cell2)
        (empty cell4)
        (empty cell6)
        (empty cell7)
        (empty cell8)
        (empty cell12)
        (at worker1 cell10)
        (at box4 cell11)
        (at box3 cell9)
        (at box2 cell5)
        (at box1 cell3)
        
        
    )
    (:goal (and 
        (at box1 cell1)
        (at box2 cell6)
        (at box3 cell7)
        (at box4 cell12))
    )
)
